"use client";

// import type { Metadata } from 'next'

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { usePathname } from "next/navigation";
import Homepage from "@/components/homepage/Homepage";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  console.log("pathname", pathname);
  return (
    <html lang="en">
      <body className={inter.className}>
        {pathname === "/" ? <Homepage /> : <Navbar />}
        {children}
        <Footer />
      </body>
    </html>
  );
}
